# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

daemon:

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false

  httpProxy: "http://squid.slac.stanford.edu:3128"
  httpsProxy: "http://squid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,idds-dev-daemon,panda-dev-server,panda-dev-jedi"

  panda:
    panda_url_ssl: https://panda-dev-server:25443/server/panda
    panda_url: http://panda-dev-server:25080/server/panda
    panda_monitor_url: "https://panda-dev-server"
    pandacache_url: https://panda-dev-server:25443/server/panda

  conductor:
    brokers: activemq-dev
    port: 61613
    destination: /queue/iddspanda
    username: FIXME_WRITER
    password: FIXME_PASS

rest:

  iddsServer: idds-dev.slac.stanford.edu

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false

  httpProxy: "http://squid.slac.stanford.edu:3128"
  httpsProxy: "http://squid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,idds-dev-daemon,panda-dev-server,panda-dev-jedi"

  panda:
    panda_url_ssl: https://panda-dev-server:25443/server/panda
    panda_url: http://panda-dev-server:25080/server/panda
    panda_monitor_url: "https://panda-dev-server"
    pandacache_url: https://panda-dev-server:25443/server/panda

  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: idds-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: idds-dev-main-tlssan-cert
        hosts:
          - domain: slac.stanford.edu
            hostOverride: idds-dev.slac.stanford.edu

postgres:

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
