# Default values for panda.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jedi:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false

server:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false

  # use Route class for ingress
  route:
    enabled: false
  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: panda-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: panda-k8s-dev-jedi-tls-cert
        hosts:
          - domain: slac.stanford.edu
            hostOverride: panda-dev.slac.stanford.edu

  # ID token of the PanDA service account
  authIdToken: "FIXME"

  # VO (. role) of the ID token
  authVO: "panda_dev.production"

postgres:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
