{{- if .Values.panda.enabled }}

{{- $auth_providers := list -}}
{{- range $provider, $value := .Values.bigmon.auth.providers -}}
{{- $auth_providers = append $auth_providers $provider -}}
{{- end }}

# panda configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-bigmon-envs
type: Opaque
stringData:
  # bigmon
  BIGMON_HOST: "{{ .Values.bigmon.hostname }}"
  BIGMON_NUM_WSGI_PROC: "{{ .Values.bigmon.numWSGI }}"
  BIGMON_SECRET_KEY: "{{ .Values.bigmon.secretKey }}"
  BIGMON_VO: "{{ .Values.bigmon.vo }}"
  BIGMON_DEPLOYMENT: "{{ .Values.bigmon.deployment }}"
  {{- if .Values.bigmon.debugMode }}
  BIGMON_DEBUG: "True"
  {{- else }}
  BIGMON_DEBUG: "False"
  {{- end }}

  # Auth
  BIGMON_AUTH_PROVIDER_LIST: {{ join "," $auth_providers | quote}}
  {{- range $provider, $value := .Values.bigmon.auth.providers}}
  SOCIAL_AUTH_{{upper $provider}}_KEY: {{$value.key}}
  SOCIAL_AUTH_{{upper $provider}}_SECRET: {{$value.secret}}
  {{- end }}
  SOCIAL_AUTH_INDIGOIAMOIDC_BASEPATH:  "{{ .Values.auth.indigoiam.basePath }}"


  # PandaDB
  PANDA_DB_NAME: "{{ .Values.panda.database.name }}"
  PANDA_DB_HOST: "{{ .Values.panda.database.dbhost | default (printf "%s-postgres" (include "panda_ref" .)) }}"
  PANDA_DB_PORT: "{{ .Values.panda.database.port }}"
  PANDA_DB_USER: "{{ .Values.panda.database.user }}"
  PANDA_DB_PASSWORD: {{ .Values.panda.database.password }}
  
  # iDDS
  IDDS_DB_NAME: "{{ .Values.idds.database.name}}"
  IDDS_DB_HOST: "{{ .Values.idds.database.host | default (printf "%s-postgres" (include "idds_ref" .)) }}"
  IDDS_DB_PORT: "5432"
  IDDS_DB_USER: "{{ .Values.idds.database.user}}"
  IDDS_DB_PASSWORD: "{{ .Values.idds.database.password}}"

  IDDS_HOST: "{{ include "idds_ref" . }}-rest"

  # Rucio
  RUCIO_SERVER_HOST: "{{ .Values.rucio.rucioHost }}"
  RUCIO_AUTH_HOST: "{{ .Values.rucio.authHost }}"
  RUCIO_ACCOUNT: "{{ .Values.rucio.account }}"
  RUCIO_USERNAME: "{{ .Values.rucio.username }}"
  RUCIO_PASSWORD: "{{ .Values.rucio.password }}"

  # CRIC
  CRIC_API_URL: "{{ .Values.cric.apiUrl }}"

  # AWS
  AWS_ACCESS_KEY_ATLAS: "{{ .Values.aws.accessKey }}"
  AWS_SECRET_KEY_ATLAS: "{{ .Values.aws.secretKey }}"

  {{ include "set_proxy" . | indent 2 }}

---
# certs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-bigmon-certs
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/bigmon_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

{{- end }}
