{{- if .Values.iam.enabled }}
# IAM configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-db-envs
type: Opaque
stringData:
  MARIADB_USER: {{ .Values.iam.database.user }}
  MARIADB_PASSWORD: {{ .Values.iam.database.password }}
  MARIADB_ROOT_PASSWORD: {{ .Values.iam.database.password }}_admin

---
# iam envs
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-envs
type: Opaque
stringData:
  # IAM_JAVA_OPTS: "-Dspring.profiles.active={{ .Values.iam.profiles }} -Dspring.data.rest.basePath=/iam -Dserver.servlet.context-path=/iam -Dlog4j2.formatMsgNoLookups=true"
  IAM_JAVA_OPTS: "-Dspring.profiles.active={{ .Values.iam.profiles }} -Dlog4j2.formatMsgNoLookups=true"

  {{- if .Values.iam.database.host }}
  IAM_DB_HOST: {{.Values.iam.database.host}}
  {{- else }}
  IAM_DB_HOST: "{{ include "add_affix" (list .Values.affix "iam") }}-mariadb"
  {{- end }}
  IAM_DB_NAME: {{.Values.iam.database.name}}
  IAM_DB_USERNAME: {{.Values.iam.database.user}}
  IAM_DB_PASSWORD: {{.Values.iam.database.password}}
  IAM_CILOGON_CLIENT_ID: {{ .Values.iam.cilogon.client_id}}
  IAM_CILOGON_CLIENT_SECRET: {{ .Values.iam.cilogon.client_secret}}

  IAM_PORT: "8080"

  IAM_ORGANISATION_NAME: "Rubin"
  IAM_TOPBAR_TITLE: "PanDA Rubin"
  IAM_ACCESS_TOKEN_INCLUDE_AUTHN_INFO: "true"
  IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY: "hidden"
  IAM_CLIENT_REGISTRATION_ALLOW_FOR: REGISTERED_USERS
  IAM_LOCAL_AUTHN_ENABLED_FOR: vo-admins
  IAM_REGISTRATION_REQUIRE_EXTERNAL_AUTHENTICATION: "true"
  IAM_LOGO_URL: "https://atlpan.web.cern.ch/atlpan/PanDA-rev-logo-300.jpg"
  IAM_LOGO_HEIGHT: "200"
  IAM_LOGO_WIDTH: "200"
  IAM_REGISTRATION_OIDC_ISSUER: "https://cilogon.org"

  IAM_BASE_URL: "https://panda-iam-dev.cern.ch"
  IAM_ISSUER: "https://panda-iam-dev.cern.ch"
  IAM_USE_FORWARDED_HEADERS: "true"
  IAM_KEY_STORE_LOCATION: "file:///indigo-iam/config//iam-keystore.jwks"

  IAM_MAIL_HOST: "smtp.cern.ch"
  IAM_MAIL_PORT: "587"
  IAM_NOTIFICATION_FROM: "panda-doma-no-reply@cern.ch"
  IAM_NOTIFICATION_ADMIN_ADDRESS: "panda-doma-admins@cern.ch"


---
# init db
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-initdb
type: Opaque
stringData:
  init_org_db.sql: |-
    CREATE DATABASE {{.Values.iam.database.name}} CHARACTER SET latin1 COLLATE latin1_swedish_ci;
    GRANT ALL PRIVILEGES on {{.Values.iam.database.name}}.* to '{{ .Values.iam.database.user }}'@'%' identified by '{{ .Values.iam.database.password }}';


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-conf
type: Opaque
stringData:
  {{- range $path, $_ := .Files.Glob "files/iam_conf/*" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4}}
  {{- end }}

{{- end }}
