{{- if .Values.idds.enabled }}

{{- $client_vos := list -}}
{{- range $client := .Values.auth.oidc.clients -}}
{{- $client_vos = append $client_vos $client.name -}}
{{- end }}

# iDDS configuration
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-idds-db-envs
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.idds.database.name }}"
  POSTGRES_USER: "{{ .Values.idds.database.user }}"
  POSTGRES_PASSWORD: "{{ .Values.idds.database.password }}"
  POSTGRES_SCHEMA: "{{ .Values.idds.database.schema }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-idds-envs
type: Opaque
stringData:
  PANDA_AUTH_ID_TOKEN: "{{ .Values.auth.authIdToken }}"
  PANDA_AUTH_VO: "{{ .Values.auth.authVO }}"
  PANDA_AUTH: "{{ .Values.auth.auth }}"

  PANDA_BEHIND_REAL_LB: "1"
  PANDA_MONITOR_URL: "https://{{ include "bigmon_ref" . }}-main"
  PANDA_URL: "http://{{ include "panda_ref" . }}-server:{{ .Values.panda.port }}/server/panda"
  PANDA_URL_SSL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/server/panda"
  PANDACACHE_URL: "https://{{ include "panda_ref" . }}-server:{{ .Values.panda.sslPort }}/server/panda"
  PANDA_VERIFY_HOST: "{{ .Values.panda.verifyHost}}"
  PANDA_CONFIG_ROOT: "{{ .Values.panda.configRoot}}"

  IDDS_DATABASE_NAME: "{{ .Values.idds.database.name}}"
  IDDS_DATABASE_USER: "{{ .Values.idds.database.user}}"
  IDDS_DATABASE_PASSWORD: "{{ .Values.idds.database.password}}"
  IDDS_DATABASE_SCHEMA: "{{ .Values.idds.database.schema}}"

  IDDS_DATABASE_HOST: "{{ .Values.idds.database.host | default (printf "%s-postgres" (include "idds_ref" .)) }}"

  IDDS_CONDUCTOR_BROKERS: "{{ include "msgsvc_ref" . }}-activemq:61613"
  IDDS_CONDUCTOR_PORT: "61613"
  IDDS_CONDUCTOR_DESTINATION: "/queue/idds_panda"
  IDDS_CONDUCTOR_USERNAME: "idds"
  IDDS_CONDUCTOR_PASSWORD: "{{.Values.msgsvc.basePasswd}}_idds"

  IDDS_RECEIVER_BROKERS: "{{ include "msgsvc_ref" . }}-activemq:61613"
  IDDS_RECEIVER_PORT: "61613"
  IDDS_RECEIVER_DESTINATION: "/queue/panda_idds"
  IDDS_RECEIVER_USERNAME: "idds"
  IDDS_RECEIVER_PASSWORD: "{{.Values.msgsvc.basePasswd}}_idds"

  IDDS_SERVER: "https://{{ include "idds_ref" . }}:{{ .Values.idds.restPort  }}"

  {{ include "set_proxy" . | indent 2 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-idds-auth
type: Opaque
stringData:
  "auth.cfg.json": |-
      {"/opt/idds/config/idds/auth.cfg":
          {"common":
              {"allow_vos": {{ join "," $client_vos | quote}}
              },
          {{- range $client := .Values.auth.oidc.clients }}
          {{$client.name | quote }}{{":"}}
            {{- $.Files.Get "files/panda_auths/auth_config.json.template" | replace "ID" $client.client_id | replace "SECRET" $client.client_secret | replace "URL" $.Values.auth.oidc.config_url | replace "AUDIENCE" $.Values.auth.oidc.audience  | replace "NAME" $client.name }}
            {{ "," }}
          {{- end }}
          "test_vo": {"a": "b"}
          }
      }
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-idds-certs
type: Opaque
data:
  {{- range $path, $_ := .Files.Glob "files/idds_certs/**.pem" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-idds-tls-certs
type: kubernetes.io/tls
data:
  tls.crt: |-
    {{ $.Files.Get "files/idds_certs/hostcert.pem" | b64enc }}
  tls.key: |-
    {{ $.Files.Get "files/idds_certs/hostkey.pem" | b64enc }}

{{- end }}
