# mariadb secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-mariadb
type: Opaque
data:
  root_password: {{ .Values.iam.database.root_password | b64enc }}
  database_name: {{ .Values.iam.database.name | b64enc }}
  user_name: {{ .Values.iam.database.user | b64enc }}
  user_password: {{ .Values.iam.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-iam-mariadb-id-rsa
type: Opaque
data:
  id_rsa: |-
    {{ $.Files.Get "files/mariadb_conf/id_rsa" | b64enc }}

---
# harvester db
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-mariadb
type: Opaque
data:
  root_password: {{ .Values.harvester.database.admin_password | b64enc }}
  database_name: {{ "harvester" | b64enc }}
  user_name: {{ "harvester" | b64enc }}
  user_password: {{ .Values.harvester.database.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets.fullname" . }}-harvester-mariadb-id-rsa
type: Opaque
data:
  id_rsa: |-
    {{ $.Files.Get "files/mariadb_conf/id_rsa" | b64enc }}
