# Default values for harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

harvester:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false

  httpProxy: "http://squid.slac.stanford.edu:3128"
  httpsProxy: "http://squid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,panda-dev-server"

  experiment: "lsst"
  pilotcerts:
    enabled: true

mariadb:
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    selector: false
