# Default values for harvester.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  secret: "panda-secrets"
  # externally reachable URLs templated into configuration files that need them
  # (must be overridden per-environment, e.g. in values/values-ds.yaml)
  endpoints:
    pandaHost: "" # e.g. panda-server-blabla.cern.ch, useful for e.g. harvester IamTokenCredManager target_list
    pandaUrl: "" # e.g. https://panda-server-blabla.cern.ch
    bigmonUrl: "" # e.g. https://bigmon-blabla.cern.ch
    rucioUrl: "" # e.g. https://rucio-blabla.cern.ch:443
    rucioAuthUrl: "" # e.g. https://rucio-blabla-auth.cern.ch:443
    cricUrl: "" # e.g. https://datalake-cric.cern.ch

harvester:
  # enable harvester
  enabled: true
  # container image and tag
  image:
    tag: "v0.7.6"
    # tag: "v0.7.5"
    # tag: "v0.6.5"
    # tag: "v0.6.1"
    # tag: "master"

  # PV with selector support
  #persistentvolume:
  #    selector: false

  # Experiment
  experiment: ""

  # http/s proxy if containers need it to access external services
  #httpProxy: "http://proxy.sdcc.bnl.local:3128"
  #httpsProxy: "http://proxy.sdcc.bnl.local:3128"

  # run containers with no-root PID e.g. for OKD
  #noRoot: true
  
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "50Gi"
    requests:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "30Gi"

  pilot:
    url: "" # e.g. https://cern.ch/atlas-panda-pilot/pilot3-3.14.0.tar.gz
    caPath: "" # e.g. /etc/grid-security/certificates or a CVMFS folder, if pilot needs to verify HTTPS connections

mariadb:
  # enable database
  enabled: true

  # PV with selector support
  #persistentvolume:
  #    selector: false

  image:
      repository: bitnami/mariadb
      pullPolicy: IfNotPresent
      # tag: "10.11.11"
      tag: "latest"
 
  resources:
    limits:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "50Gi"
    requests:
      cpu: 4000m
      memory: 16Gi
      ephemeral-storage: "30Gi"
