#!/bin/bash
set -m
/data/panda/init-panda
/data/panda/run-panda-crons &

if [[ -z "${PANDA_NO_ROOT}" ]]; then
  runuser -u atlpan -g zp -- /etc/rc.d/init.d/httpd-pandasrv start
else
  /etc/rc.d/init.d/httpd-pandasrv start
fi
