# pv
{{- if .Values.persistentvolume.create }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}
  labels:
      {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  capacity:
    storage: {{ .Values.persistentvolume.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.persistentvolume.path }}
---
{{- end }}
# pv claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistentvolume.class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentvolume.size }}
  {{- if .Values.persistentvolume.create }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "main.fullname" . }}
  labels:
    {{- include "main.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "main.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "main.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "main.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["/bin/sh", "-c"]
          args:
            - cp /data/bigmon/configmap/* /data/bigmon/config/ ;
              python /data/bigmon/config/process_template.py ;
              {{- if .Values.autoStart }}
              until /usr/pgsql-*/bin/pg_isready -h ${PANDA_DB_HOST} -p ${PANDA_DB_PORT}; do echo waiting for database; sleep 2; done;
              start-daemon.sh all
              {{- else }}
              sleep infinity & wait
              {{- end }}
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
              - name: {{ include "main.fullname" . }}-logs
                mountPath: /data/bigmon/logs
              - name: {{ include "main.fullname" . }}-configmap
                mountPath: /data/bigmon/configmap
              - name: {{ include "main.fullname" . }}-certs
                mountPath: /opt/bigmon/etc/cert
          envFrom:
            - secretRef:
                name: {{ .Values.global.secret }}-bigmon-envs
            - configMapRef:
                name: {{ include "main.fullname" . }}-env
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "main.fullname" . }}-logs
          persistentVolumeClaim:
            claimName: {{ include "main.fullname" . }}
        - name: {{ include "main.fullname" . }}-configmap
          configMap:
              name: {{ include "main.fullname" . }}-configmap
        - name: {{ include "main.fullname" . }}-certs
          secret:
              secretName: {{ .Values.global.secret }}-bigmon-certs
