apiVersion: v1
kind: Service

metadata:
  name: mariadb-server
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: server

  ports:
    - name: mysql
      port: 3306
