apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: panda-harvester
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PanDAWMS/panda-k8s
    targetRevision: main
    path: helm/harvester
    helm:
      valueFiles:
        - values.yaml
        - values/values-atlas_testbed.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: panda-harvester
      jsonPointers:
        - /spec/volumeClaimTemplates
