# Default values for bigmon.
# # This is a YAML-formatted file.
# # Declare variables to be passed into your templates.
#

main:
  persistentvolume:
    create: false
    sharedPvcName: panda-shared-logs
    subPath: bigmon-logs
    size: 50Gi

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-doma.cern.ch
        paths:
          - path: /condor_logs
            pathType: Prefix
            serviceName: panda-harvester
            servicePort: 443
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: panda-doma.cern.ch
