# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:
  replicaCount: 1
  iddsServer: rubin-panda-idds-dev.slac.stanford.edu

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    size: 50Gi
    selector: false

  persistentvolumerequests:
    create: false
    class: sdf-data-rubin
    size: 1000Gi
    selector: false
    path: "/data/idds-requests"
    requestpath: "/data/idds-requests/panda_jobs/panda/idds-requests"

  persistentvolumerequests_test:
    create: false
    class: wekafs--sdf-k8s01
    size: 1000Gi
    selector: false
    path: "/data/idds-requests"
    requestpath: "/data/idds-requests/panda_jobs/panda/idds-requests"

  resources:
    limits:
      cpu: 4000m
      memory: 32Gi
    requests:
      cpu: 4000m
      memory: 32Gi

  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: rubin-panda-idds-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: slac.stanford.edu
            hostOverride: rubin-panda-idds-dev.slac.stanford.edu

postgres:
  enabled: false

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    size: 50Gi
