# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

rest:
  replicaCount: 1
  iddsServer: panda-idds-doma.cern.ch

  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  serverConf:
    minWorkers: "4"
    maxWorkers: "8"
    numWsgi: "2"
    numWsgiThread: "4"
    maxBacklog: "50"

  ingress:
    enabled: true
    hosts:
      - domain: cern.ch
        hostOverride: panda-idds-doma.cern.ch
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: cern.ch
            hostOverride: panda-idds-doma.cern.ch

postgres:
  enabled: false

  resources:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 2000m
      memory: 8Gi
