# Default values for idds.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

daemon:

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    size: 50Gi

  httpProxy: "http://squid.slac.stanford.edu:3128"
  httpsProxy: "http://squid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,idds-dev-daemon,panda-dev-server,panda-dev-jedi"

rest:

  iddsServer: rubin-panda-idds-dev.slac.stanford.edu

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    size: 50Gi

  httpProxy: "http://squid.slac.stanford.edu:3128"
  httpsProxy: "http://squid.slac.stanford.edu:3128"
  noProxy: "localhost,idds-dev-rest,idds-dev-daemon,panda-dev-server,panda-dev-jedi"

  ingress:
    enabled: true
    hosts:
      - domain: slac.stanford.edu
        hostOverride: rubin-panda-idds-dev.slac.stanford.edu
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: "default"
        hosts:
          - domain: slac.stanford.edu
            hostOverride: rubin-panda-idds-dev.slac.stanford.edu

postgres:

  # PV: For use cases that users are not allowed to create PV,
  # please update class to corresponding storageclass and update create to false.
  persistentvolume:
    class: wekafs--sdf-k8s01
    create: false
    size: 30Gi
