#!/bin/bash

use_default=1

if [[ ! -z "${EXPERIMENT}" ]]; then
    init_script=/opt/harvester/sandbox/${EXPERIMENT}.init-harvester
    if [ -f ${init_script} ]; then
        echo "Executing ${init_script}"
        bash $init_script
        use_default=0
    fi
fi

if [ ${use_default} -eq 1 ]; then
    echo "Executing default init-harvester"

    # install CA files
    /opt/harvester/bin/panda_common-install_igtf_ca > /var/log/panda/install_igtf_ca.log 2>&1

    # condor logs
    mkdir -p /var/log/panda/condor_logs
    chmod 777 /var/log/panda/condor_logs
fi
