#!/bin/bash
#
use_default=1

if [[ -z "${EXPERIMENT}" ]]; then
    run_script = /opt/harvester/sandbox/${EXPERIMENT}.run-harvester-crons
    if [ -f ${run_script} ]; then
        echo "Executing ${run_script}"
        $run_script
        use_default=0
    fi
fi

if [ ${use_default} -eq 1 ]; then
    echo "Executing default run-harvester-crons"
    # refresh CA files
    while true; do sleep 36000; /opt/harvester/bin/panda_common-install_igtf_ca > /var/log/panda/install_igtf_ca.log 2>&1; done &
fi
