#!/bin/bash

# refresh CA files
while true; do sleep 36000; /opt/harvester/bin/panda_common-install_igtf_ca > /var/log/panda/install_igtf_ca.log 2>&1; done &

if [[ ! -z "${EXPERIMENT}" ]]; then
    CurrentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    run_script=${CurrentDir}/${EXPERIMENT}.run-harvester-crons
    if [[ -f ${run_script} ]]; then
        echo "Executing ${run_script}"
        bash $run_script &
    fi
fi
