#!/bin/bash

if [ ${HARVESTER_DB_HOST_ADD_INDEX} == "true" ]; then
    if [[ ! -z "${HARVESTER_DB_HOST_DOMAIN}" ]]; then
        export HARVESTER_DB_HOST=${HARVESTER_DB_HOST_PREFIX}-${HOSTNAME##*-}.${HARVESTER_DB_HOST_DOMAIN}
    else
        export HARVESTER_DB_HOST=${HARVESTER_DB_HOST_PREFIX}-${HOSTNAME##*-}
    fi

    if [[ ! -z "${MARIADB_DATABASE_PREFIX}" ]]; then
        export MARIADB_DATABASE=${MARIADB_DATABASE_PREFIX}-${HOSTNAME##*-}
    fi
fi

export CLOUDSDK_CONFIG=/data/harvester/gcloud_config
export KUBECONFIG=/data/harvester/gcloud_config/.kube
