#!/bin/bash

echo "setup harvester env"

if [[ ! -z "${EXPERIMENT}" ]]; then
    echo "setup experiment ${EXPERIMENT} environment"
    CurrentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    setup_script=${CurrentDir}/${EXPERIMENT}.setup-harvester
    if [[ -f ${setup_script} ]]; then
        echo "Executing ${setup_script}"
        source ${setup_script}
    fi
fi
