# PV: For use cases that users are not allowed to create PV,
# please update class to corresponding storageclass and update create to false.
activemq:
  persistentvolume:
    create: false
    class: wekafs--sdf-k8s01
    path: "/mnt/activemq-data"
    size: 50Gi
    selector: false
